name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt-core & dbt-snowflake
        run: |
          pip install dbt-core~=1.8 dbt-snowflake~=1.8

      - name: Install dependencies
        run: dbt deps

      - name: Lint YAML and Jinja
        run: |
          pip install yamllint jinja2-cli
          yamllint .

      - name: Dry run dbt seed + run-operation
        run: |
          dbt seed --show --full-refresh
          dbt run-operation create_snowpipes --args '{"run_queries": false}'
